// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function GetRequests() {
  return window['go']['main']['App']['GetRequests']();
}

export function GetVariables() {
  return window['go']['main']['App']['GetVariables']();
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveVariables(arg1) {
  return window['go']['main']['App']['SaveVariables'](arg1);
}

export function SendRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4, arg5);
}
