// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteRequest(arg1:string):Promise<void>;

export function GetRequests():Promise<Array<main.Request>>;

export function GetVariables():Promise<string>;

export function SaveRequest(arg1:main.Request):Promise<string>;

export function SaveVariables(arg1:string):Promise<string>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ResponseMsg>;
